### ISSUE TITLE
Copy license to licences/ dir

### ISSUE THREAD

**Issue by theirix** [bincrafters/conan-templates#14]
Should not line 
https://github.com/bincrafters/conan-templates/blob/338460d535f4d8003388d33fbc21a63498972e3b/conanfile.py#L59

be as suggested by [official manual](http://docs.conan.io/en/latest/packaging/bintray/conan_center_guide.html)?

`self.copy("license*", dst="licenses",  ignore_case=True, keep_path=False)`

**Comment by uilianries** [comment]
i agree with @theirix

**Comment by solvingj** [comment]
To be clear, that line in the documentation is just an example that is trying to demonstrate Conan's flexibility of pattern matching and `ignore_case` option, not a recommendation of best practice.  Half the licenses are named `COPYING` afterall.   

For the record, regarding "standards" in the bodies of each of the Conan methods as "unenforceable".  That is to say, if I see three different recipes using any of the three lines below: 
1. `self.copy("LICENSE")`
1. `self.copy("license*", ignore_case=True, keep_path=False)`
1. `self.copy("LICENSE.txt", dst="licenses", src="sources")`

I don't consider any of them wrong, assuming they actually capture the license file for that library.  So, what we're really talking about at the moment is, what should the template say... and what should our guideline be. 

With that said,  I'm not at all opposed to setting `dst="licenses"` on the template now, and planning to backport the change to old repositories later.  Go ahead and make that change in the template. I thought putting licenses in a subfolder was just one person's convention, and so i disregarded it.  I was not aware of that line in the documentation.  Because it's in the documentation, it will likely become a "convention" across the whole of Conan community, and it costs us nothing to comply. 

However, our bincrafters `LICENSE.md` file would also be captured and put in the package, and we definitely don't want that, so we will have to add `src=self.source_subfolder` to our template. 

On the topic of the `license*` pattern with `ignore_case=True`, again I think it was just demonstrating flexibility, and that specifying the precise license filename for each library (`LICENSE` or `COPYING`) is better.  But, if you really like the approach used in the example, please go ahead and change it.  We can discuss further if anyone has any objection in the future.

**Comment by theirix** [comment]
Of course, different packages use different names. Proposed change just suggests a good way to handle license for a package creator in case he forgots.

Totally agree about `src`, we missed it once.

**Comment by solvingj** [comment]
Sounds good.
