### ISSUE TITLE
Adding custom remotes

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/conan-templates#27]
Hi!

I'm toying around with this template for a few of my own recipes, but is not fully sure how to "insert" custom remotes (for example my own personal bintray repo).

I saw `CONAN_REMOTES` mentioned in a few places, but what would be the most straight forward way to do this so that it is propagated to travis & appveyor builds..?

Thanks!

**Comment by uilianries** [comment]
Hi @helmesjo !

We use this template in all our projects, so if you are interested to customize `CONAN_REMOTES` I see three options:

- Insert CONAN_REMOTES on your environment variables (Travis, Appveyor, ...)
- Insert CONAN_REMOTES on CI files (.travis.yml, appveryor.yml, ...)
- Fork this project, and customize the build.py to set CONAN_REMOTES

Conan team uses the second option, but we use `bincrafters-package-tools` to set our variables.

Personally I used first option for many time, but if you dont have a helper to set the variables by the API, and you use the manual way for each new project, it could be really boring.

I'm lazy, so I prefer the third option, because build.py is only executed by CI. When I need to create a package on my machine (running docker) I use just `conan create`.

**Comment by helmesjo** [comment]
I'll be going for the third option as well, as currently it's only needed in one package... :) 

Could it be something to perhaps add to this template? Maybe an `./additional-remotes.txt` that gets absorbed by `build.py` automatically? I can imagine this requirement arise for lots of users, where a package under development might require another package also under development (both currently stored in a personal repository).

Anyways, thank you for the help!

**Comment by helmesjo** [comment]
@uilianries Could you post a small example of how to properly set `CONAN_REMOTES` in build.py? Can't find any documentation on this... 

Thanks!

**Comment by uilianries** [comment]
On the example below, I used getenv to check CONAN_REMOTES from the environment variable. If doesn't exist, so it will use the default remotes. I used Bincrafters' repo but you could use another one.

The point is that ConanMultiPackager uses remotes parameter to set it arguments, or the env var `CONAN_REMOTES`. You could consume an external file as you said, read it content and set the remotes, but as I said, I'm lazy so I prefer to use the shortest way.

```python
from cpt.packager import ConanMultiPackager
import os

if __name__ == "__main__":
    default_remotes = "https://api.bintray.com/conan/bincrafters/public-conan"
    remotes = os.getenv("CONAN_REMOTES", default_remotes)
    builder = ConanMultiPackager(remotes=remotes)
    builder.add_common_builds()
    builder.run()
```

Conan package tools has some better explanation about remotes here: https://github.com/conan-io/conan-package-tools#working-with-bintray-configuring-repositories

**Comment by uilianries** [comment]
> Could it be something to perhaps add to this template? Maybe an ./additional-remotes.txt that gets absorbed by build.py automatically? I can imagine this requirement arise for lots of users, where a package under development might require another package also under development (both currently stored in a personal repository).

Good question. But this template does not set the remotes, as I said, we use [bincrafters-package-tools](https://github.com/bincrafters/bincrafters-package-tools). In the past we customized it to receive remotes from env vars, but add a custom file, as your suggestion could be a good feature IMO.

WDYT @SSE4 @solvingj ?

**Comment by SSE4** [comment]
I have no objections on external file(s), if it doesn't break anything

**Comment by helmesjo** [comment]
Great, thanks!

Btw, `CONAN_UPLOAD_ONLY_WHEN_STABLE=0` appears to be overridden, even though I set it to `0` (also tried `False`) in both appveyor.yml & as an environment variable through the webpage.
I have `CONAN_CHANNEL="testing"`.

From log:
`Skipping upload, not stable channel`

**Comment by uilianries** [comment]
That's weird, because we provide support to get from the envs:

https://github.com/bincrafters/bincrafters-package-tools/blob/master/bincrafters/build_shared.py#L118

I'll check this later. Thanks for report.

**Comment by helmesjo** [comment]
Another oddity (or just me missing something)... With the following envars defined
`CONAN_STABLE_BRANCH_PATTERN=testing/*`
`CONAN_CHANNEL=testing`
it will upload the packages, but to the branch `stable`. 
Expected package on bintray: `2.5.14:testing`
Actual package: `2.5.14:stable`

**Comment by uilianries** [comment]
seems buggy. We use the branch name as Conan channel, but CONAN_CHANNEL should be able to override this.

Thanks again to report this.

**Comment by helmesjo** [comment]
Actually, the current git-branch in my case is `testing/2.5.14`, so the `stable` part is picked up from somewhere else.

**Comment by helmesjo** [comment]
I've found [some](https://github.com/conan-io/conan-package-tools/issues/28) old & closed but still related issues regarding envars & what actually gets precedence in the end... 

@lasote Any current issues with this or should we open a new bug in [conan-package-tools](https://github.com/conan-io/conan-package-tools/)? 

Mentioned above:
1. `CONAN_UPLOAD_ONLY_WHEN_STABLE`-check appears to be ignored.
2. `CONAN_CHANNEL` appears to not be used when setting upload channel (uploaded packages on bintray are `stable` regardless of this value).
3. ...

**Comment by solvingj** [comment]
Sorry for the late response on this. 

I don't have time to dig through and try to figure out exactly what's happening in this case. Obviously, it would be good if users could use Bincrafters package tools and override the parameters via environment variables in a straightforward way without forking anything. 

With that said, we created BPT basically to override some defaults from CPT and pass some shared functions to service our own use-cases.  I think some of those functions have been implemented in CPT, and actually, we could probably now submit more of them since they're tested quite a bit and just simple static helper functions.  We'll still keep BPT to set our default overrides and stuff, but the more code we can move to CPT, the better. 

Anyone want to volunteer to copy and paste some of our more generic functions into PR's to CPT?

**Comment by solvingj** [comment]
ping @helmesjo, is this ok to close?

**Comment by helmesjo** [comment]
@solvingj 
Well, currently I don't use `CONAN_STABLE_BRANCH_PATTERN=testing/*` (I just use `stable` instead), but if nothing has changed there the bug might still be present.

With that said, it's awfully quiet in here so I'm guessing this isn't too much of an issue currently. So lets close it for now, and it can be reopened if necessary. :)
